### ISSUE TITLE
[REFACTOR] enum 업데이트 및 커스텀 예외 처리 적용

### ISSUE THREAD

**Issue by yeni-choi** [local-mood/localmood-server#25]
# 🤹리팩토링 개요
- enum 타입들에 대한 필드 추가를 진행했습니다. 
- 커스텀 에처 처리를 추가하여, 에러 발생 시 errorcode와 message, solution을 넘기도록 구현했습니다.
- 기존 CurationService에 예외 처리를 적용하였습니다. 
- Repository에서 ID에 해당하는 엔터티를 찾거나, 없을 시 errorcode로 예외를 던지는 RepositoryUtil을 생성하였습니다. 
- RepositoryUtil을 core 모듈에 생성하기 위하여 JPA를 dependency에 추가하였습니다.

### ✅ To-do
- [x] enum 필드 추가
- [x] 커스텀 예외 처리 추가
- [x] 커스텀 예외 처리 CurationService에 적용
- [x] RepositoryUtil 생성 
- [x] JPA 의존성 추가

### 📦 Related Branches
- refactor/25-enum-and-error-handling
