### ISSUE TITLE
[REFACTOR] 공간기록 중복 작성 방지

### ISSUE THREAD

**Issue by yeni-choi** [local-mood/localmood-server#273]
# 🤹리팩토링 개요
공간기록 중복 작성을 방지하기 위하여,
장소 관련 API 응답에 공간기록 작성 여부를 추가 

### ✅ To-do
- [x] 공간 상세 조회 API 리팩토링  
- [x] 멤버별 스크랩 장소 목록 조회 API 리팩토링
- [x] 장소명 검색 API 리팩토링
- [x] 장소 키워드 검색 API 리팩토링

### 📦 Related Branches
-
